name: Build this Docker image
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: docker build -t statping .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -p 8080:8080 -v /sys/fs/cgroup:/sys/fs/cgroup:ro statping

      - name: Verify App is running.
        run: docker exec --tty test-container curl -i http://localhost:8080
        
  testing:
    name: testing
    runs-on: ubuntu-latest
    needs: test
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: devopsansiblede/statping:testing

        
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: testing
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: devopsansiblede/statping:latest

